fixing missing yaml indentation simplifying command which fails:
/var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:166:in `start_command': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:94:in `save_buildpack_info'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:60:in `block in stage_application'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
        from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_application'
        from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'

FAILED
Server error, status code: 400, error code: 170001, message: Staging error: cannot get instances since staging failed

TIP: use 'cf.exe logs diag-buildpack --recent' for more information